"""update User model

Revision ID: 89fd9b5eb6b4
Revises: b259beb285dd
Create Date: 2024-08-14 15:25:59.254404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89fd9b5eb6b4'
down_revision = 'b259beb285dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_user_username')
        batch_op.create_index(batch_op.f('ix_user_user_name'), ['user_name'], unique=True)
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_user_name'))
        batch_op.create_index('ix_user_username', ['username'], unique=False)
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
